#!/usr/bin/env zsh

STOW_DIRS=(
    bat
    git
    ghostty
    idea
    lazygit
    oh-my-posh
    tmux
    zsh
)
TARGET_DIR=~

install_dir() {
    dir=$1
    echo "Install '$dir'"
    stow -R -t $TARGET_DIR $dir
}

dir=$1
if [ -n "$dir" ]; then
    install_dir $dir 
else
    for dir in $STOW_DIRS; do
	install_dir $dir
    done
fi
