#!/usr/bin/env zsh

STOW_DIRS=(
    git
    idea
    zsh
)
TARGET_DIR=~

stow_dir() {
    dir=$1
    stow -v -R -t $TARGET_DIR $dir
}

dir=$1
echo "Dir is '$dir'"
if [ -n "$dir" ]; then
    stow_dir $dir 
else
    for dir in $STOW_DIRS; do
	stow_dir $dir
    done
fi


