#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar=(
  position=top
  height=38
  color=$COLOR_MANTLE
  padding_left=16
  padding_right=16
)
sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  icon.color=$COLOR_TEXT
  icon.padding_left=10
  icon.padding_right=4
  label.font="SF Pro:Semibold:15.0"
  label.color=$COLOR_TEXT
  label.padding_left=4
  label.padding_right=10
  background.color=$COLOR_BASE
  background.corner_radius=8
  background.height=24
)
sketchybar --default "${default[@]}"

# Left side items
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

# Right side items
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/temp.sh
source $ITEM_DIR/fan.sh
source $ITEM_DIR/svim.sh

sketchybar --update
