set -g default-terminal "tmux-256color"
set -g status-position top
set -g pane-border-status top
set -g pane-border-format ' #{pane_current_path} • #{pane_current_command} '

# Keybindings

set -g prefix C-a
bind-key C-a send-prefix

bind-key r source-file ~/.tmux.conf

bind-key | split-window -h
bind-key – split-window -v

bind-key C-j resize-pane -D 5
bind-key C-k resize-pane -U 5
bind-key C-l resize-pane -R 5
bind-key C-h resize-pane -L 5

bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U

bind-key & kill-window
bind-key x kill-pane

# Theme

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "#{@thm_bg}"

set -g @catppuccin_battery_icon " "
set -g @catppuccin_cpu_icon " "

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Plugins

set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
