set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind – split-window -v

bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5
bind C-h resize-pane -L 5

unbind h
bind h select-pane -L

unbind l
bind l select-pane -R

unbind j
bind j select-pane -D

unbind k
bind k select-pane -U

unbind r
bind r source-file ~/.tmux.conf
